# 
#  User configuration
# 

title:  Gacon

# The unique resource location of your page.
# Set to `https://<username>.github.io` when hosting on GitHub Pages
url:  https://gacon.id

# Set to '' when hosting a blog on GitHub Pages, ie on `//<username>.github.io`
# Set to '/<reponame>' when using the `gh-pages` branch of a repository
baseurl: ""

# A very short description of your page
# tagline:             ""

# A short description of the page, used in the sidebar and as fallback for the meta description tag.
# Markdown enabled, but don't use more than one paragraph (enforced by `>`)
description:  >
  Nah!

# This should be the same author as first entry in `_data/authors.yml`
author:
  name: Gacon

# Fallback image and color
image:  
color:  '#4f86aa'

# Set your Google Analytics id to receive `pageview` events.
# To remove Google Anaylics from your page, remove the line below.
# google_analytics: 

# Setting a disqus shortname will enable the comment section on pages with `comments: true` in the front matter
disqus: True
disqus_shortname: gaconid

# This text will appear in the footer of every page. Markdown enabled.
copyright:  '&copy; 2020 &#124; Gacon.id'

# Format of the permalinks
permalink:  /post/:title/

# Pagination configuration (used by the `blog` layout)
paginate: 6
paginate_path:  '/page/:num/'

# Set to true when building with the `--lsi` option
# See: https://jekyllrb.com/docs/variables/#site-variables
# use_lsi:             true

# 
#  Collections
# 

collections:
  featured_categories:
    permalink:  /category/:name/
    output: true
  featured_tags:
    permalink:  /tag/:name/
    output: true
  page:
    permalink:  /insight/:path/
    output: true

# 
#  Advanced configuration
# 

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-archives

exclude:
  - README.md
  - LICENSE.md
  - Gemfile

kramdown:
  footnote_backlink:  '&#x21a9;&#xfe0e;'
  math_engine:  mathjax
  math_engine_opts:
    preview:  true
    preview_as_code:  true

compress_html:
  comments: ["<!-- ", " -->"]
  clippings:  all
  endings:  all
  ignore:
    envs: [development]

sass:
  style:  compressed

tipue_search:
  include:
    pages: false
    collections: []
  exclude:
    files: [search.html, index.html, tags.html]
    categories: []
    tags: []